#!/bin/bash -e
# @author Vincenzo Esposito (v.esposito@voismart.it)
# Hints and code taken also from https://proandroiddev.com/tutorial-compile-openssl-to-1-1-1-for-android-application-87137968fee

set -e

# Source variables from config.conf file
. config.conf


##############################################################################
############################      FUNCTIONS     ##############################
##############################################################################

function initialSetup {
    CUR_DIR="$(pwd)"
    OPENSSL_SRC_PATH="$DOWNLOAD_DIR/${OPENSSL_DIR_NAME}"
    OPENSSL_TMP_FOLDER="/tmp/openssl"
}

function setupPathsAndExports {
    NDK_PATH="$DOWNLOAD_DIR/${NDK_DIR_NAME}"
    LIB_PATH="${OPENSSL_BUILD_OUT_PATH}/libs"
    LOG_PATH="${OPENSSL_BUILD_OUT_PATH}/logs"

    # Required for OpenSSL + new NDK
    export ANDROID_NDK_HOME="$NDK_PATH"
    export ANDROID_NDK_ROOT="$NDK_PATH"

    TOOLCHAIN_PATH="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin"

    export PATH="$TOOLCHAIN_PATH:$PATH"

    # Android API (needed by OpenSSL)
    export ANDROID_API="${OPENSSL_TARGET_NDK_LEVEL}"
}

function clearBuildDirectory {
    rm -rf "${OPENSSL_BUILD_OUT_PATH}"
    mkdir -p "${LIB_PATH}"
    mkdir -p "${LOG_PATH}"
}

function clearTmpDirectory {
    rm -rf "$OPENSSL_TMP_FOLDER"
    mkdir -p "$OPENSSL_TMP_FOLDER"
    cp -r "${OPENSSL_SRC_PATH}"/* "${OPENSSL_TMP_FOLDER}"
}

function getArchitecture {
    OPENSSL_TARGET_ABI=$1

    case "$OPENSSL_TARGET_ABI" in

        armeabi-v7a)
            ARCHITECTURE="android-arm"
            export CC="armv7a-linux-androideabi${ANDROID_API}-clang"
            ;;

        arm64-v8a)
            ARCHITECTURE="android-arm64"
            export CC="aarch64-linux-android${ANDROID_API}-clang"
            ;;

        x86)
            ARCHITECTURE="android-x86 no-asm"
            export CC="i686-linux-android${ANDROID_API}-clang"
            ;;

        x86_64)
            ARCHITECTURE="android-x86_64"
            export CC="x86_64-linux-android${ANDROID_API}-clang"
            ;;

        *)
            echo "Unsupported ABI: $OPENSSL_TARGET_ABI"
            exit 1
            ;;
    esac

    export AR="llvm-ar"
    export RANLIB="llvm-ranlib"
}


##############################################################################
############################        INIT          ############################
##############################################################################

# Initial variables setup
initialSetup
# Set final paths and exports
setupPathsAndExports
# Clear and recreate the build output directory
clearBuildDirectory
# Set clang compiler, instead of gcc by default
# No longer required with newer NDK versions, which use clang by default, but leaving it here for older NDK compatibility
# CC=clang


##############################################################################
############################        MAIN          ############################
##############################################################################

# Build OpenSSL for each ARCH specified in config.conf
for arch in "${TARGET_ARCHS[@]}"
do
    echo "======================================"
    echo "Configuring OpenSSL for target arch $arch ..."
    echo "======================================"

    # Clear the tmp source directory
    clearTmpDirectory
    # Go to source files
    cd ${OPENSSL_TMP_FOLDER}

    OPENSSL_OUTPUT_PATH=$LIB_PATH/$arch

    # Set the target architecture
    # Can be android-arm, android-arm64, android-x86 etc
    getArchitecture $arch

    echo "Using:"
    echo "  ARCH=$ARCHITECTURE"
    echo "  CC=$CC"

    # Create Makefile
    ./Configure $ARCHITECTURE -D__ANDROID_API__="$ANDROID_API" >> "${LOG_PATH}/${arch}.log" 2>&1

    # Build Openssl
    echo "Building OpenSSL Library for Android arch $arch"
    make clean >> "${LOG_PATH}/${arch}.log" 2>&1
    make -j$(nproc) >> "${LOG_PATH}/${arch}.log" 2>&1

    # Output folders
    mkdir -p "$OPENSSL_OUTPUT_PATH/lib"
    mkdir -p "$OPENSSL_OUTPUT_PATH/include"

    # Copy Headers
    cp -RL include/openssl "$OPENSSL_OUTPUT_PATH/include"

    # Copy Static libs
    cp libssl.a "$OPENSSL_OUTPUT_PATH/lib"
    cp libcrypto.a "$OPENSSL_OUTPUT_PATH/lib"

    echo "Build completed for $arch"
done


##############################################################################
############################### CLEANUP ######################################
##############################################################################

rm -rf "$OPENSSL_TMP_FOLDER"

echo "======================================"
echo "Finished building OpenSSL!"
echo "Output: $OPENSSL_BUILD_OUT_PATH"
echo "======================================"
